### ISSUE TITLE
Create the Students Projects section 

### ISSUE THREAD

**Issue by AppleC4T** [fossasia/gci18.fossasia.org#106]
**Actual Behaviour**

No Students Projects section on the website.

**Expected Behaviour**

Students Projects section on the website, with an option to add projects.

**Would you like to work on the issue?**

Yes, I’ll work on it.

**Comment by niteshkumarniranjan** [comment]
@AppleC4T I have already created it but someone's PR has removed the link.  Check it out: https://gci18.fossasia.org/projects.html
