### ISSUE TITLE
Remove unwanted files from the repository

### ISSUE THREAD

**Issue by venkateshdb** [fossasia/gci18.fossasia.org#111]
**Actual Behaviour**

There are lots of unnecessary files present in repository Which should be removed.
Like unwanted html files, images etc

**Expected Behaviour**

Unwanted files removed.

**Would you like to work on the issue?**

Any one can do it.

**Comment by saarthakchats** [comment]
I'll do it 👍

**Comment by abishekvashok** [comment]
Solved in #120
