### ISSUE TITLE
My first Issue

### ISSUE THREAD

**Issue by RahulMetre03** [fossasia/gci18.fossasia.org#122]
**Actual Behaviour**

**Expected Behaviour**

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

**Comment by sarnava1** [comment]
Welcome to Fossasia. @RahulMetre03 please fill the issue template.

**Comment by STEdirisuriya** [comment]
@RahulMetre03 Welcome. If you like to contribute you can make issue that contains on the project or you can solve a issue already there.
