### ISSUE TITLE
Add Instructions to Run GCI'18 Website locally

### ISSUE THREAD

**Issue by fragm3** [fossasia/gci18.fossasia.org#140]
**Actual Behaviour**

Currently, no instructions are present to run https://gci18.fossasia.org/ locally on your computer.

**Expected Behaviour**

Add Instructions for running https://gci18.fossasia.org/ locally on your computer.

**Helpful Links**

https://jekyllrb.com/

**Would you like to work on the issue?**

No

**Comment by STEdirisuriya** [comment]
I am working on this,
