### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/gci18.fossasia.org#142]
**Actual Behaviour**

Only basic instructions

**Expected Behaviour**

More details for all participants like me including
- Adding a mentor
- Adding a photo nick
- Adding a language to Thank You Section

**Steps to reproduce it**

Document and add all of these

**Screenshots of the issue**

<img width="1363" alt="screenshot 2018-10-30 at 6 44 09 pm" src="https://user-images.githubusercontent.com/24372680/47721159-86768a00-dc75-11e8-97b4-b513da380315.png">

**Would you like to work on the issue?**

Yes, working on it!

**Comment by abishekvashok** [comment]
Add this to readme.md

**Comment by abishekvashok** [comment]
Please work on this instead: https://github.com/fossasia/gci18.fossasia.org/issues/61
