### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by KSNINJA** [fossasia/gci18.fossasia.org#146]
**Actual Behaviour**
1. The student's section is hiding behind the image . The images are too large making them   unreadable.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/26023139/47725971-9abf8480-dc7f-11e8-95b4-848326314284.png">

2. The link to the project's section in header is missing . 
3. The social media section and the two section , one above and one below it , have same background colour which makes it difficult to distinguish between them .
4. The Video in the videos section is out of its place.

![](https://user-images.githubusercontent.com/33794760/47618548-9ddd3800-dafa-11e8-835e-de4f8c2c691b.png)

**Comment by saarthakchats** [comment]
I had fixed the video thing

**Comment by liveHarshit** [comment]
One and four are resolved
