### ISSUE TITLE
Contributors in the Contributors' section are ordered randomly

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/gci18.fossasia.org#166]
**Actual Behaviour**

Random Order

**Expected Behaviour**

Should be according to number of contributions, or most recent commits or something

**Steps to reproduce it**

Make necessary code changes

**Screenshots of the issue**

<img width="1220" alt="screenshot 2018-11-01 at 8 02 21 am" src="https://user-images.githubusercontent.com/24372680/47829267-83ca8080-ddac-11e8-98d2-87e10daa8f8c.png">
The order is changing on my laptop every time I reload, there must be some minor bug

**Would you like to work on the issue?**

Open to all

**Comment by niteshkumarniranjan** [comment]
@saarthakchats I think It has been fixed you can close this issue now.
