### ISSUE TITLE
Project Section needs to be improved

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/gci18.fossasia.org#168]
**Actual Behaviour**

On hover, shows only the name of the project

**Expected Behaviour**

Should also give the name of the creator and details of the project

**Steps to reproduce it**

Make necessary code changes

**Screenshots of the issue**

<img width="1256" alt="screenshot 2018-11-01 at 8 31 05 am" src="https://user-images.githubusercontent.com/24372680/47830120-7fa06200-ddb0-11e8-8809-bd6f87f5c1ea.png">

**Would you like to work on the issue?**

Yes

**Comment by SarthakSri98** [comment]
I am a newbie to open source and would also like to work on this issue.

**Comment by saarthakchats** [comment]
Okay, make a PR @SarthakSri98 and link it to this issue 👍

**Comment by SarthakSri98** [comment]
Thank you, that's very nice of you!
