### ISSUE TITLE
Unused .pug file

### ISSUE THREAD

**Issue by niteshkumarniranjan** [fossasia/gci18.fossasia.org#170]
**Actual Behaviour**

Unnecessary index.pug file

**Expected Behaviour**

Should be no index.pug

**Steps to reproduce it**

https://github.com/fossasia/gci18.fossasia.org/blob/master/index.pug

**Would you like to work on the issue?**
Yes / Open to GCI Participants

**Comment by prateekiiest** [comment]
Please follow the fossasia guidelines and rename the issue with a suitable comprehensive name

**Comment by saarthakchats** [comment]
@niteshkumarniranjan 
That file is for the Thank You JS effect

**Comment by saarthakchats** [comment]
If you would like to remove it, you'll have to reinstate the JS effect somehow, up to you

**Comment by niteshkumarniranjan** [comment]
@saarthakchats I think you haven't read the docs carefully. Try removing the file it also works there is no need of a .pug file.

**Comment by saarthakchats** [comment]
Okay
