### ISSUE TITLE
Add Up Communication Section in Readme

### ISSUE THREAD

**Issue by sk9331657** [fossasia/gci18.fossasia.org#173]
**Actual Behaviour**
There is no communication section present in Readme.

**Expected Behaviour**
Add Communication Section similar to one in this https://github.com/fossasia/badgeyay.

**Would you like to work on the issue?**
No, GCI Candidates can work on this.

**Comment by sk9331657** [comment]
Go ahead.

**Comment by rishabhgoel14** [comment]
@sk9331657 Under which section I have to add communication section

**Comment by sk9331657** [comment]
You have to add communication section readme.
