### ISSUE TITLE
Add .DS_Store in gitignore

### ISSUE THREAD

**Issue by fragm3** [fossasia/gci18.fossasia.org#178]
**Actual Behaviour**

Files like .DS_Store, etc are not present in .gitignore

**Expected Behaviour**

Should be present, so that meta data files are ignored in PR for students.

**Would you like to work on the issue?**

No, GCI participants can take this up.

**Comment by ammarbinfaisal** [comment]
> Files like .DS_Store, etc
what other than .DS_Store should be there?

**Comment by fragm3** [comment]
.vscode can be also added. These 2 for the time being
