### ISSUE TITLE
The landing page is

### ISSUE THREAD

**Issue by SarthakSri98** [fossasia/gci18.fossasia.org#181]
**Actual Behaviour**

The landing page background is too dense so it is difficult to read letter with while or so color
**Expected Behaviour**

The landing page should be more attractive so that the people coming must have a great first impression.
**Steps to reproduce it**

I will put up a layer of div over the first page with a transparent color so that it can cover the background a bit. Otherwise I will just try to blur the background with filter:blur
**Screenshots of the issue**

![screenshot from 2018-11-02 07-29-29](https://user-images.githubusercontent.com/28146914/47878464-5a5d3380-de44-11e8-9b50-8937bb5e4e14.png)

**Would you like to work on the issue?**
Yes

**Comment by fragm3** [comment]
PR: https://github.com/fossasia/gci18.fossasia.org/pull/544 tackles this, so closing it.
