### ISSUE TITLE
Add social media feed

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/gci18.fossasia.org#185]
**Actual Behaviour**

There's only social media section link which provides you to visit those social media.

**Expected Behaviour**

It needs to add a feed for FB, youtube,... for view instance without going to the social media page.

**Would you like to work on the issue?**

yes, I'm working.

**Comment by myfrom** [comment]
While you're at it I think it might be worth to also move the Twitter feed from the bottom to the social section.

**Comment by STEdirisuriya** [comment]
@myfrom yes, I'll
