### ISSUE TITLE
Add translations for Readme.md

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/gci18.fossasia.org#190]
**Actual Behaviour**

The readme.md only appears in English. Some of us not familiar with English.

**Expected Behaviour**

Add translations of readme.md in other languages and add links into original readme.md

**Steps to reproduce it**

Make another folder to locate these files and add your translations of readme.md into it.

**Would you like to work on the issue?**

All of us, need to get together for work.

**Comment by Ritzing** [comment]
I would like to take up this issue
