### ISSUE TITLE
Add translation for website.

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/gci18.fossasia.org#191]
**Actual Behaviour**

The website only in English.

**Expected Behaviour**

It needs to add more languages.

**Steps to reproduce it**

We can use G translate or JS method to store strings and show them. Suggest your ideas.

**Would you like to work on the issue?**

All of us.

**Comment by subhahu123** [comment]
we can use translator plugin given by google
https://translate.google.com/manager/website/

**Comment by STEdirisuriya** [comment]
@subhahu123 Yes. But Gtranslate isn't perfect much for all languages.

**Comment by soniasingla** [comment]
Hii @STEdirisuriya :)
Can I work on this issue, specific for hindi and punjabi langugae?

**Comment by STEdirisuriya** [comment]
@soniasingla yes sure, But this is issue not to translate text in thankyou.js this issue is for translating whole web page.
