### ISSUE TITLE
Map isn't responsive!

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/gci18.fossasia.org#229]
**Actual Behaviour**

map isn't responsive. It overflows. 
![image](https://user-images.githubusercontent.com/33794760/48003834-95f24900-e135-11e8-8f88-42a4d89a723b.png)

**Expected Behaviour**

Make it responsive

**Would you like to work on the issue?**

Yes

**Comment by amrs-tech** [comment]
I'd like to work on this issue. But may i know what's that location so that i can embed it in the page

**Comment by STEdirisuriya** [comment]
@amrs-tech Sorry, I am working on this.
