### ISSUE TITLE
Add Travis Checks for image dimensions

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/gci18.fossasia.org#236]
Ping @abishekvashok 
Should I attempt to do it using https://github.com/abishekvashok/img_checker 
Will this be an advanced issue?

**Comment by saarthakchats** [comment]
Can you guide me with this @abishekvashok ?
I would like to work on it

**Comment by abishekvashok** [comment]
@sarthakchats you can use that, it would be an advanced issue, I reckon, if you could apply the tests and fix the failing ones as well.

**Comment by saarthakchats** [comment]
@abishekvashok Someone will have to enable to repo on Travis right?

**Comment by abishekvashok** [comment]
@saarthakchats please make it work on your fork, show it, then I will enable Travis CI.

**Comment by saarthakchats** [comment]
@abishekvashok Can you add the advanced issue tag to this?

**Comment by saarthakchats** [comment]
![33717206-10eafcdc-db7f-11e7-802c-da1fd8650772](https://user-images.githubusercontent.com/24372680/48081293-ac6fd180-e215-11e8-91e1-8b6d871886d0.png)

**Comment by saarthakchats** [comment]
See the tests work

**Comment by saarthakchats** [comment]
<img width="989" alt="screenshot 2018-11-06 at 10 52 41 pm" src="https://user-images.githubusercontent.com/24372680/48081722-b2b27d80-e216-11e8-8bef-ee3f2a61c9a4.png">
