### ISSUE TITLE
Improved UX for Mentor Section

### ISSUE THREAD

**Issue by niteshkumarniranjan** [fossasia/gci18.fossasia.org#27]
**Current Behavior**
3-col Grid is used
Icons are too small
Spacing is inconsistent

**Expected Behavior**
4-col Grid can be used
Icon should be little large (a/c Google 30px is required for mobile devices)
UI can be Improved

**Want to Work**
Yes

**Comment by myfrom** [comment]
Hi!
Sorry, but are you still working on this?
And if you are, is it also fixing #54?
If you aren't working on that, would you mind if I take it as part of GCI task?

**Comment by niteshkumarniranjan** [comment]
I have completed it already my my last PR is pending but you can work on it you want. @myfrom

**Comment by myfrom** [comment]
Oh, ok. Sorry, I didn't see your PR.

**Comment by niteshkumarniranjan** [comment]
@myfrom you can do same for student section

**Comment by liveHarshit** [comment]
@niteshkumarniranjan Make it similar to https://gci17.fossasia.org/ and add some mentors also.
