### ISSUE TITLE
Geolocations are not added for any mentors

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/gci18.fossasia.org#283]
**Actual Behaviour**

No Geolocation added for mentors in the mentors.yml file

**Expected Behaviour**

Should be added so that it can later be implemented onto the map

**Steps to reproduce it**

- Choose a mentor and ask him/her to provide the geolocation using https://github.com/fossasia/geolocation
- All mentors from #96
- Go to mentors.yml and add the `lat` and `lng`
**LogCat for the issue**

**Screenshots of the issue**

**Would you like to work on the issue?**

Open to all

**Comment by akshit15013** [comment]
I what to work on this issue

**Comment by saarthakchats** [comment]
Yes good, everyone can work on this @akshit15013
