### ISSUE TITLE
Update the social media links in the footer section

### ISSUE THREAD

**Issue by amrs-tech** [fossasia/gci18.fossasia.org#29]
Clicking on the social media icons take s to the top of the page. Need to be updated with proper link reference.

**Comment by saarthakchats** [comment]
I'll work on it

**Comment by PAPERPANKS** [comment]
can you mention link for the respective icon @amrs-tech

**Comment by AppleC4T** [comment]
Can I work on adding more links and icons to the footer or are you guys working on it now?

**Comment by liveHarshit** [comment]
> Can I work on adding more links and icons to the footer or are you guys working on it now?

Go ahead. The task is open for all.

**Comment by AppleC4T** [comment]
Ok, I'm working on it then.

**Comment by saarthakchats** [comment]
#130

**Comment by saarthakchats** [comment]
#132

**Comment by saarthakchats** [comment]
#134

**Comment by saarthakchats** [comment]
@amrs-tech I have updated the footer links, close this issue now 💯
