### ISSUE TITLE
Improvements required in the fossasia projects sections

### ISSUE THREAD

**Issue by ammarbinfaisal** [fossasia/gci18.fossasia.org#295]
**Obvious improvements that are required**

* There is no margin b/w individual projects that should be 20 - 25px
* chat.susi.ai's screenshot has been taken is  dark mode while all other projects are having light backgrounds. chat.susi.ai's screenshot should be in light mode unless mentors want otherwise.

**Would you like to work on the issue?**

I would but anyone else can also work on it

**Comment by Sid911** [comment]
Working on it..
