### ISSUE TITLE
Weird hover over images(mentor, students and other such images)

### ISSUE THREAD

**Issue by ammarbinfaisal** [fossasia/gci18.fossasia.org#296]
**Actual Behaviour**

Hovering over the area below an image also causes that images to be overlaid by a shadow.

![gci18site](https://user-images.githubusercontent.com/30975614/48301382-2accbc00-e513-11e8-9c57-677b4575134a.gif)

**Expected Behaviour**

hovering over the actual image should cause that

**Steps to reproduce it**

Go to the [website](https://gci8.fossasia.org)

**Would you like to work on the issue?**

Open for all

**Comment by subhahu123** [comment]
this is not for only student section
but for whole website 
for icon image

**Comment by ammarbinfaisal** [comment]
Yes, it is. I think I mentioned that in the title. Still thank you

**Comment by subhahu123** [comment]
Not only that 
i was working on the issue i came to know that hover section and some parts are badly coded
they have bad coding style which make redundany and difficult to correct this 
because i have to make changes in different tag 

bad style of coding

**Comment by abishekvashok** [comment]
Closing since it's fixed as of now
