### ISSUE TITLE
Need to give shape to the website

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/gci18.fossasia.org#3]
Currently, the entire site is a template. Need to add basic initial content so that all participants(including me) will be able to understand and contribute better.

**Comment by abhilashk433** [comment]
Hi @saarthakchats . I would love to work on this issue.

**Comment by saarthakchats** [comment]
Hi @abhilashk433 
Sure, this issue is assigned to all GCI participants and mentors.
We'll all work on it together.
You can start making contribs if you'd like

**Comment by abishekvashok** [comment]
Hi, we would be opening multiple issues for the same. Currently for the sake of maintainabiloty shall I close this?

Please do wait for gci to start to claim tasks :)

**Comment by saarthakchats** [comment]
@abishekvashok 
Yes, we'll wait for GCI
We'll do it when we register as participants :)

**Comment by saarthakchats** [comment]
Close the issue if you feel that it is important
