### ISSUE TITLE
Add Chinese (Traditional) to the Thank You Section

### ISSUE THREAD

**Issue by Ryan10145** [fossasia/gci18.fossasia.org#320]
**Actual Behaviour**

The current Thank You section contains only Chinese (Simplified). However, people in Hong Kong/Taiwan use primarily Chinese (Traditional), which should be added.

**Expected Behaviour**

A message in Chinese (Traditional) should be added.

**Would you like to work on the issue?**

Yes

**Comment by akshit15013** [comment]
Can I work on this issue?
