### ISSUE TITLE
Add A Photo Nick to the GCI FOSSASIA Site Student Section and Connect with Projects on GitHub - FOSSASIA

### ISSUE THREAD

**Issue by abhinavraj0123456789** [fossasia/gci18.fossasia.org#33]
Issue number: 33
Detail describing things done in PR: In this PR the picture is added to "img" folder and student details is added into the file "students.yml" inside the "data" folder.
Link to website: (i) https://github.com/abhinavraj0123456789/gci18.fossasia.org
(ii) https://github.com/fossasia/gci18.fossasia.org/issues/33

**Comment by abishekvashok** [comment]
We don't need issues for this
