### ISSUE TITLE
Fossasia Album imgages are not Loading in firefox (  .webp loaded error )

### ISSUE THREAD

**Issue by subhahu123** [fossasia/gci18.fossasia.org#427]
Fossasia Album is not working in firefox . firefox could not loaded the images in format   .webp
i checked in chrome it's working but not in firefox . I tried to download the image and then try to open in firefox but it was not able to show the image
Also the fourth slide on main page ....

![screenshot from 2018-11-20 22-39-56](https://user-images.githubusercontent.com/34541684/48790456-5cb10000-ed15-11e8-81a2-8310883ad4ef.png)

![peek 2018-11-20 22-43](https://user-images.githubusercontent.com/34541684/48790740-11e3b800-ed16-11e8-9889-4014d5f42157.gif)

![screenshot from 2018-11-20 22-49-01](https://user-images.githubusercontent.com/34541684/48791037-c4b41600-ed16-11e8-8500-2834ffbed71c.png)

**Comment by subhahu123** [comment]
@Ryan10145  check ..that if u also facing same problem or not
may there is a other issue with my browser ...so that's why i m asking
@fragm3

**Comment by ammarbinfaisal** [comment]
webp doesnt has a very good support. check [this](https://caniuse.com/#feat=webp)  
we can use jpg and the images can be compressed wtih [squoosh.app](https://squoosh.app)

**Comment by Sid911** [comment]
the latest firefox has the support for Webp

**Comment by subhahu123** [comment]
> webp doesnt has a very good support. check [this](https://caniuse.com/#feat=webp)
> we can use jpg and the images can be compressed wtih [squoosh.app](https://squoosh.app)

we can but it will affect the speed

**Comment by subhahu123** [comment]
> the latest firefox has the support for Webp

i have the updated one but its not working...............

**Comment by Sid911** [comment]
@subhahu123  that will take a lot of performance hit in our already heavy site

**Comment by ammarbinfaisal** [comment]
> the latest firefox has the support for Webp

the stable one(v62) doesnt have. v65 has as far as i know but it isnt released is it? and even if it gets released safari doesnt supports webp

> we can but it will affect the speed

I lately compressed and degraded a jpeg - reduced its size from 1.4mb to 400kb using squoosh.app and the new image looked almost same

**Comment by subhahu123** [comment]
we show add both  one as fallout one
if one fails then only others load

**Comment by Sid911** [comment]
@subhahu123 I will add a jpeg version as fallout if you are not working on it.... just need a bit of time to convert (all images) the webP to jpeg

**Comment by subhahu123** [comment]
go ahead
