### ISSUE TITLE
High load times and very high cpu usage

### ISSUE THREAD

**Issue by Sid911** [fossasia/gci18.fossasia.org#429]
**Actual Behaviour**

Right now the website Is having many elements which are being  parsed and processing while the page loads, which in turn gives very large load times and system usage
**Expected Behaviour**

The website should be fast To load and should lazy load the sections once the user scrolls down, this will cut down the initial usage and spread out evenly when the user scrolls down.

**Proposal**
Adding a lazy loading system to the website

**Would you like to work on the issue?**

anyone can work on it

**Comment by Sid911** [comment]
@fragm3 @jogendra Should we add lazy loading system?

**Comment by fragm3** [comment]
@Sid911 yes, that would be good approach. You can tackle one section at a time.

**Comment by KSNINJA** [comment]
I am working on this .
