### ISSUE TITLE
Add nick image

### ISSUE THREAD

**Issue by KSNINJA** [fossasia/gci18.fossasia.org#43]
Added the Nick images to the Mentors and Students section
Included Screenshots of the changes in the mentors.yml and students.yml  . 
Added nick images to img/mentors and img/students

Link to the repo - https://github.com/KSNINJA/gci18.fossasia.org
Link to the hosted website. - https://ksninja.github.io/gci18.fossasia.org/

![image](https://user-images.githubusercontent.com/26023139/47544776-5c843700-d906-11e8-8cd1-6c5925071aa5.png)

![image](https://user-images.githubusercontent.com/26023139/47544797-7291f780-d906-11e8-8388-ba9a51d1047a.png)

**Comment by abishekvashok** [comment]
You need to make a pr. Please make a pr.

**Comment by KSNINJA** [comment]
I added the link to the PR
