### ISSUE TITLE
Add more Social Media links to the Social Media Section

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/gci18.fossasia.org#49]
**Actual Behaviour**

Only Twitter and Facebook present

**Expected Behaviour**

All should be there

**Steps to reproduce it**

- Add the icons
- Add the links

**Screenshots of the issue**
<img width="1347" alt="screen shot 2018-10-26 at 8 53 27 pm" src="https://user-images.githubusercontent.com/24372680/47576073-363fb500-d961-11e8-8fca-949f0e34cb99.png">

**Would you like to work on the issue?**

Yes, working on it.

**Comment by liveHarshit** [comment]
Issue #29 is same.
