### ISSUE TITLE
Remove unwanted files and compress images.

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/gci18.fossasia.org#496]
**Actual Behaviour**

There are a lot of files unwanted and useless. (Images, Videos, HTML theme files...) 
A lot of images need to compress. 

**Expected Behaviour**

Remove unwanted and unused files, decrease the size of repo to maintain a perfect repository. #188 
Compress all the images.

**Would you like to work on the issue?**

Yes of course!

**Comment by niteshkumarniranjan** [comment]
@STEdirisuriya Have you checked #480 and #476

**Comment by abishekvashok** [comment]
Ref #188
