### ISSUE TITLE
Extra space in the connect section

### ISSUE THREAD

**Issue by Ridvmodi** [fossasia/gci18.fossasia.org#540]
**Actual Behaviour**
![screenshot 289](https://user-images.githubusercontent.com/38110540/49330358-61966f00-f5b3-11e8-863f-881b2824979d.png)

This space in the connect section
**Expected Behaviour**
![screenshot 290](https://user-images.githubusercontent.com/38110540/49330366-973b5800-f5b3-11e8-8644-5d3b94130676.png)

**Would you like to work on the issue?**
Yes

**Comment by KSNINJA** [comment]
The social widgets are no longer there . This can be closed
