### ISSUE TITLE
Photos don't behave correctly in different aspect ratios

### ISSUE THREAD

**Issue by jakubpawlina** [fossasia/gci18.fossasia.org#566]
**Actual Behaviour**

Photos of mentors and students don't behave correctly when window width is between `990px` and `770px`.

**Expected Behaviour**

Correctly scaled photos.

**Steps to reproduce it**

Change photos proportions in proper width.

**Screenshots of the issue**

![zrzut ekranu 132](https://user-images.githubusercontent.com/29257057/49525763-be916e00-f8ae-11e8-8559-668ce3beb7c6.png)

**Would you like to work on the issue?**

Open for all

**Comment by Dharmesh-Poddar** [comment]
please specify more on it I didn't got any issue in aspect ratio on my phone and laptop!!

**Comment by ammarbinfaisal** [comment]
@Dharmesh-Poddar the section isn't responsive. nothing related to aspect ratios

**Comment by jakubpawlina** [comment]
@ammarbinfaisal you are a bit right - it is responsive, but doesn't work correct every time @Dharmesh-Poddar try to decrease width of the browser's window and you will see the problem - I haven't been precise in specifying the issue

**Comment by jakubpawlina** [comment]
Of course, I've updated it

**Comment by Ryan10145** [comment]
I would like to work on this

**Comment by jakubpawlina** [comment]
Great! Thank you :)
