### ISSUE TITLE
Improve performance by adding asynchronous scripts

### ISSUE THREAD

**Issue by AppleC4T** [fossasia/gci18.fossasia.org#587]
**Actual Behaviour**
The page takes a lot of time to load, especially on mobile.

**Expected Behaviour**
The performance can be improved by loading some scripts asynchronously (especially the APIs)

**Would you like to work on the issue?**
Yes.

**Comment by ammarbinfaisal** [comment]
this woudl be very good. but the rest of the files which are loading directly would have to bundled I guess. what do you think? #578
