### ISSUE TITLE
Fix extra spaces in contributor's section

### ISSUE THREAD

**Issue by KSNINJA** [fossasia/gci18.fossasia.org#612]
**Actual Behaviour**
There are some long names , which are taking the card below it to move to an next line .

**Screenshots of the issue**
<img width="1440" alt="screenshot 2018-12-09 at 8 05 37 pm" src="https://user-images.githubusercontent.com/26023139/49698771-6af48c80-fbee-11e8-9122-76dfd3013147.png">

**Would you like to work on the issue?**
Open to all

**Comment by AppleC4T** [comment]
The Students section has the same problem. It would be nice if you could fix it as well since it's probably caused by the same bug.
![image](https://user-images.githubusercontent.com/34106174/49701192-80b38300-fbe9-11e8-8ef1-408037e84cad.png)
