### ISSUE TITLE
Add missing mentors to website

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci18.fossasia.org#635]
List of Mentors
* [x] Jogendra | Kumar
* [ ] Wei Tat | Chung
* [x] Shubham | Gupta
* [ ] Shubham | Kumar
* [ ] Soong Chee | Gi
* [x] Akshat | Garg
* [ ] Abhijeet Singh | Khangarot
* [ ] Tarun | Kumar
* [x] Abishek | V Ashok
* [ ] SARNAVA | KONAR
* [ ] Eden | D
* [ ] Harshit | Khandelwal
* [ ] Hong Phuc | Dang
* [x] Akshat | Jain
* [ ] simranpreet | kaur
* [ ] ROHIT | POTTER
* [ ] Nikit | Bhandari
* [ ] Priyanshu | Khandelwal
* [ ] André | Rebentisch
* [ ] Sanskar | Jethi
* [x] Anshuman | Verma
* [ ] Mayank | Vaidya
* [ ] THIYAGARAJ | T
* [ ] Prateek | Chanda
* [ ] Shubham | Kumar Singh
* [x] Arundhati | Gupta
* [ ] Chashmeet | Singh
* [ ] Madhushanka | Padmal
* [ ] Abhinav | Raj
* [ ] Praveen | Ojha
* [ ] Harsh | Patel
* [ ] Anup | Panwar
* [ ] Praduman | Singh
* [ ] Sridhar | Jajoo
* [ ] Mohit | Sharma
* [ ] Suneet | Srivastava
* [ ] Dilpreet | Singh
* [ ] Rupav | Jain
* [ ] Pranjal | Paliwal

**Comment by Dharmesh-Poddar** [comment]
@mariobehling I would like to work on it..

**Comment by NishithP2004** [comment]
@abishekvashok @fragm3 Please Update this ,so that I can know exactly which Mentors I should add. Many of the mentors are added to the site.
