### ISSUE TITLE
Pictures are not showing

### ISSUE THREAD

**Issue by pprathameshmore** [fossasia/gci18.fossasia.org#642]
**Actual Behaviour**

Currently, the website is not loading pictures.

**Expected Behaviour**

Maybe some links are broken, We should fix all the links.

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

![annotation 2018-12-26 090519](https://user-images.githubusercontent.com/17108186/50431007-784b8f80-08ed-11e9-9bdd-4e9ff5b020b3.jpg)

**Would you like to work on the issue?**

I would like to work on this issue.

**Comment by pythongiant** [comment]
SGTM. although I would recommend focusing the coding work on other projects

**Comment by pprathameshmore** [comment]
@pythongiant Okay!
