### ISSUE TITLE
add the mentors location in the map

### ISSUE THREAD

**Issue by rpotter12** [fossasia/gci18.fossasia.org#643]
**Actual Behaviour**

currently only few mentors location are there on the map.

**Expected Behaviour**

the location of all the mentors should be added to the map. :)

List of Mentors
* [ ] Jogendra | Kumar
* [ ] Wei Tat | Chung
* [ ] Shubham | Gupta
* [ ] Shubham | Kumar
* [ ] Soong Chee | Gi
* [ ] Akshat | Garg
* [ ] Abhijeet Singh | Khangarot
* [ ] Tarun | Kumar
* [ ] Abishek | V Ashok
* [ ] SARNAVA | KONAR
* [ ] Eden | D
* [ ] Harshit | Khandelwal
* [ ] Hong Phuc | Dang
* [ ] Akshat | Jain
* [ ] simranpreet | kaur
* [x] ROHIT | POTTER
* [ ] Nikit | Bhandari
* [ ] Priyanshu | Khandelwal
* [ ] André | Rebentisch
* [ ] Sanskar | Jethi
* [ ] Anshuman | Verma
* [ ] Mayank | Vaidya
* [ ] THIYAGARAJ | T
* [ ] Prateek | Chanda
* [ ] Shubham | Kumar Singh
* [ ] Arundhati | Gupta
* [ ] Chashmeet | Singh
* [ ] Madhushanka | Padmal
* [ ] Abhinav | Raj
* [ ] Praveen | Ojha
* [ ] Harsh | Patel
* [ ] Anup | Panwar
* [ ] Praduman | Singh
* [ ] Sridhar | Jajoo
* [ ] Mohit | Sharma
* [ ] Suneet | Srivastava
* [ ] Dilpreet | Singh
* [ ] Rupav | Jain
* [ ] Pranjal | Paliwal

**Comment by abishekvashok** [comment]
Students locations shouldn't be added according to gci rules.

**Comment by rpotter12** [comment]
Ok thanks :)
