### ISSUE TITLE
Add a suitable favicon to the site

### ISSUE THREAD

**Issue by sarnava1** [fossasia/gci18.fossasia.org#66]
**Actual Behaviour**
Currently there is no favicon. Please add a favicon in the site

**Expected Behaviour**
A good favicon should appear in the website

**Would you like to work on the issue?**
Open only for GCI students

**Comment by sarnava1** [comment]
Hello @mariobehling @tabesin @liveHarshit can you add the label of gci, beginner friendly and good first issue? I am not getting any such option to add labels as am not having write access.

**Comment by AppleC4T** [comment]
Working on the icon.
