### ISSUE TITLE
Add meta tags and other tags like ogp for better SEO

### ISSUE THREAD

**Issue by sarnava1** [fossasia/gci18.fossasia.org#67]
**Actual Behaviour**
Add suitable meta tags and other tags like ogp, twitter for better SEO
Presently there is no meta tags in the site.

**Expected Behaviour**
The meta and other tags will enable good SEO

**Would you like to work on the issue?**
Open only for GCI students.

**Comment by sarnava1** [comment]
Hello @mariobehling @tabesin @liveHarshit can you add the label of gci, beginner friendly and good first issue? I am not getting any such option to add labels as am not having write access.

**Comment by JamsheedMistri** [comment]
I will work on this issue.
