### ISSUE TITLE
Writings in the landing page not very clear

### ISSUE THREAD

**Issue by sarnava1** [fossasia/gci18.fossasia.org#68]
**Actual Behaviour**
The white writings in the landing page is not clear

The white writings : 
Creating collaborative open-source technologies.
Connecting Open Tech Communities all over Asia with Developers and Creators
in the FOSSASIA Network.
 **Expected Behaviour**
We should make the writings more clear

**Steps to reproduce it**
Just open the FOSSASIA site
**Screenshots of the issue**
![writingsnotclear](https://user-images.githubusercontent.com/25319565/47599694-eef10d00-d9d0-11e8-9709-a879b61fc2f1.png)
**Would you like to work on the issue?**
Only for GCI students

**Comment by sarnava1** [comment]
Hello @mariobehling @tabesin @liveHarshit can you add the label of gci too? I am not getting any such option to add labels.

**Comment by STEdirisuriya** [comment]
I would like to work on this.

**Comment by sarnava1** [comment]
@STEdirisuriya sure!!

**Comment by liveHarshit** [comment]
@STEdirisuriya try to add a shadow effect in the background.

**Comment by STEdirisuriya** [comment]
@liveHarshit ok. I'll

**Comment by STEdirisuriya** [comment]
I added the PR and it's merged. But however, after another PR, it's get lost some.

**Comment by STEdirisuriya** [comment]
I think this should closed now. @sarnava1

**Comment by jogendra** [comment]
@fragm3 @STEdirisuriya I think the issue is still there.
