### ISSUE TITLE
Create a mentors section

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci18.fossasia.org#7]
We just added a new template
Create a mentors section in the current template with the same design.

The goal would be to create a mentor section, add a mentors.yml file, define a standard format, and make a mentor appear beautifully in the site using Jekyll.

_note: be sure to ask mentors before posting any of their details_

Ref: https://GitHub.com/fossasia/gci17.fossasia.org

**Comment by saarthakchats** [comment]
Can I try working on this?

**Comment by STEdirisuriya** [comment]
I'm working on this issue.

**Comment by sahildav** [comment]
@STEdirisuriya This issue can be claimed by multiple people .
