### ISSUE TITLE
Create FOSSASIA Project Section

### ISSUE THREAD

**Issue by fragm3** [fossasia/gci18.fossasia.org#74]
**Actual Behaviour**

Currently, not present

**Expected Behaviour**

Create FOSSASIA Project Section in https://gci18.fossasia.org/ after mentor section.
Add 1 FOSSASIA open source project description.
See: https://gci17.fossasia.org/ for reference(project section of FOSSASIA after Students Projects)

**Screenshots of the issue**

<img width="1000" alt="screenshot 2018-10-27 at 4 35 29 pm" src="https://user-images.githubusercontent.com/18073126/47603206-74db7b00-da06-11e8-989c-03ae30200c9f.png">

**Would you like to work on the issue?**

Any GCI Participant

**Comment by STEdirisuriya** [comment]
@fragm3 Can I work on this issue?

**Comment by STEdirisuriya** [comment]
@fragm3 I made a PR.
