### ISSUE TITLE
Some issues need a fix.

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/gci18.fossasia.org#81]
**Actual Behaviour**

- [ ] Names and profile links of the students is not aligned center with the image.
![image](https://user-images.githubusercontent.com/33794760/47606371-525e5780-da30-11e8-949f-0d7667890b73.png)
![image](https://user-images.githubusercontent.com/33794760/47606373-66a25480-da30-11e8-8296-97a3d79bca87.png)
![image](https://user-images.githubusercontent.com/33794760/47618556-c36a4180-dafa-11e8-8459-e5d92dba3eb3.png)

- [ ] Image in the video section is overflows.
![image](https://user-images.githubusercontent.com/33794760/47618548-9ddd3800-dafa-11e8-835e-de4f8c2c691b.png)

- [ ] Text in the introduction box is not clear. (It should change the font color or make color balance of the image.)
![image](https://user-images.githubusercontent.com/33794760/47618567-da109880-dafa-11e8-8260-cb9741e5997e.png)

**Expected Behaviour**

Fix issues.

**Would you like to work on the issue?**

Opened to all.

**Comment by KSNINJA** [comment]
I fixed some issues and added my own improvements . Link to the PR -
https://github.com/fossasia/gci18.fossasia.org/pull/144

**Comment by abishekvashok** [comment]
The 2nd one was already referenced in #68
