### ISSUE TITLE
Social media section incomplete

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/gci18.fossasia.org#83]
**Actual Behaviour**

Only FB and twitter

**Expected Behaviour**

All should be there

**Steps to reproduce it**

add them

**LogCat for the issue**

**Screenshots of the issue**

<img width="1347" alt="screen shot 2018-10-26 at 8 53 27 pm" src="https://user-images.githubusercontent.com/24372680/47606614-58a20300-da33-11e8-93bf-5cc7397f87b7.png">

**Would you like to work on the issue?**

Yes

**Comment by fragm3** [comment]
Duplicate of https://github.com/fossasia/gci18.fossasia.org/issues/71

**Comment by saarthakchats** [comment]
@fragm3 
This isn't for the footer

**Comment by abishekvashok** [comment]
Please check it now.
