### ISSUE TITLE
Icons in the social media section are too small

### ISSUE THREAD

**Issue by AppleC4T** [fossasia/gci18.fossasia.org#84]
**Actual Behaviour**

The newly added social media section icons are too small. (probably caused by the foundry css files overwiting after loading)

**Expected Behaviour**

The icons are uniform in size.

![image](https://user-images.githubusercontent.com/34106174/47606670-c68c0180-da16-11e8-84fe-ef9c67b6262b.png)

**Would you like to work on the issue?**
Yes, working on it right now.

**Comment by abishekvashok** [comment]
Why was this closed?
