### ISSUE TITLE
Remove stock template sections

### ISSUE THREAD

**Issue by prox07** [fossasia/gci18.fossasia.org#93]
**Actual Behaviour**
The site contains four stock template (named Foundry) sections as of now.

**Expected Behaviour**
Sections must me removed immediately!

**Screenshots of the issue**
![screenshot from 2018-10-28 15-50-33](https://user-images.githubusercontent.com/33557095/47614714-f9430200-dac9-11e8-8808-007a0b611e5a.png)
![screenshot from 2018-10-28 15-50-36](https://user-images.githubusercontent.com/33557095/47614715-f9db9880-dac9-11e8-834c-309c12da8f0a.png)
![screenshot from 2018-10-28 15-50-39](https://user-images.githubusercontent.com/33557095/47614716-f9db9880-dac9-11e8-88de-9f3890573c98.png)
![screenshot from 2018-10-28 15-50-47](https://user-images.githubusercontent.com/33557095/47614717-f9db9880-dac9-11e8-8658-fbe27f518b84.png)

**Would you like to work on the issue?**

Yes please!

**Comment by venkateshdb** [comment]
I can do it.

**Comment by venkateshdb** [comment]
I have removed the stock templates , checkit out https://venkateshdb.github.io/gci18.fossasia.org/

**Comment by prox07** [comment]
Stop thriving off other people's work, leech.

**Comment by venkateshdb** [comment]
sorry, I thought no one is working on it , that's why i choose this issue
